In [1]:
# example of supervised and unsupervised learning

import numpy as np
import matplotlib.pyplot as plt

In [7]:
# iris data
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

iris = load_iris()
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size=0.3)

In [22]:
# multiclass classification using logistic regression
from sklearn.multiclass import OneVsRestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, classification_report
lr = LogisticRegression()
lr.fit(X_train, y_train)
y_test_pred = lr.predict(X_test)
cm = confusion_matrix(y_test, y_test_pred)
print("Confusion matrix")
print(cm)
print(classification_report(y_test, y_test_pred))

Confusion matrix
[[19  0  0]
 [ 0 13  2]
 [ 0  0 11]]
             precision    recall  f1-score   support

          0       1.00      1.00      1.00        19
          1       1.00      0.87      0.93        15
          2       0.85      1.00      0.92        11

avg / total       0.96      0.96      0.96        45



In [23]:
# unsupervised examples, k-means
# http://scikit-learn.org/stable/auto_examples/cluster/plot_kmeans_assumptions.html